#!/usr/bin/env python3
"""Stage-2 screening verdicts, keyed by review-pool index (spec v1.0 section 2).

Each verdict below was reached by reading that record's API-retrieved title and
abstract. Records excluded here fail an inclusion criterion on the face of the
retrieved text (wrong disease, wrong material, wrong article type). Everything
else becomes a CANDIDATE and is adjudicated against full text in npc_extract.py,
because "new samples" vs "public-data reuse" is a Methods-section question that an
abstract frequently cannot settle.
"""

# index -> (reason_code, quotable basis)
EXCLUDE = {
 3:   ("not_NPC_disease", "Chikungunya virus respiratory tropism; nasopharyngeal swabs, not NPC"),
 4:   ("not_NPC_disease", "juvenile nasopharyngeal angiofibroma, a benign vascular tumour, not carcinoma"),
 5:   ("not_NPC_disease", "pneumococcal colonisation of nasopharyngeal epithelium, not NPC"),
 17:  ("review", "pubType Review; METTL14 m6A narrative review"),
 18:  ("cell_line_or_xenograft_only", "four EBV-positive B-lymphoblast cell lines; NPC mentioned only as EBV-associated disease"),
 19:  ("review", "pubType Review; EBV immune microenvironment research progress"),
 26:  ("review", "pubType Review; EBV/HPV co-infection review"),
 30:  ("not_NPC_disease", "gastric cancer study; NPC named only as a cancer where WDHD1 was reported"),
 39:  ("not_NPC_disease", "long-read scRNA-seq of COVID-19 nasopharyngeal swabs"),
 43:  ("not_NPC_disease", "SARS-CoV-2 nasopharyngeal tissue, machine-learning classification"),
 48:  ("not_NPC_disease", "SARS-CoV-2 nasal immunity across variants"),
 54:  ("not_NPC_disease", "adenoid and tonsil hypertrophy in children; benign lymphoid tissue"),
 57:  ("not_NPC_disease", "SARS-CoV-2 PBMC lipid mediators"),
 72:  ("review", "pubType systematic-review/Review; progress of scRNA-seq in NPC research"),
 77:  ("review", "pubType Review; exercise-induced immune regulation"),
 79:  ("not_NPC_disease", "PGE2-EP2/EP4 Treg induction; not an NPC patient-sample study"),
 81:  ("review", "pubType Review; NPC immune archetypes classification review"),
 83:  ("not_NPC_disease", "SARS-CoV-2 nasal immunity preprint"),
 87:  ("not_NPC_disease", "COVID-19 nasopharyngeal neutrophil signatures"),
 88:  ("not_NPC_disease", "mouse nasopharyngeal lymphatic plexus and CSF drainage"),
 94:  ("not_NPC_disease", "SARS-CoV-2 human challenge study"),
 97:  ("not_NPC_disease", "RNA editing in SARS-CoV-2 infection"),
 101: ("not_nasopharyngeal_site", "oral squamous cell carcinoma primary and metastatic ecosystems"),
 105: ("not_NPC_disease", "HNSCC and DLBCL bioinformatics; no NPC single-cell samples"),
 107: ("not_NPC_disease", "COVID-19 gene regulatory networks from public scRNA-seq"),
 109: ("duplicate_conference_abstract", "meeting abstract of the Avelumab/WBRT LMD phase 1B study reported in full elsewhere in this pool"),
 114: ("not_NPC_disease", "skin cutaneous melanoma; NPC named only as a cancer where HOPX was studied"),
 116: ("not_NPC_disease", "SARS-CoV-2 breakthrough infection nasopharyngeal mucosa"),
 118: ("not_NPC_disease", "COVID-19 public scRNA-seq regulatory networks"),
 119: ("methods_tool_paper", "CamoTSS computational method; nasopharyngeal cancer used only as a demonstration dataset"),
 120: ("not_NPC_disease", "HNSCC oxidative-stress gene signature"),
 122: ("not_NPC_disease", "MAP3K19 and severe COVID-19"),
 123: ("not_NPC_disease", "maculopapular drug exanthema in COVID-19"),
 127: ("methods_tool_paper", "Bio-protocol for 3-D nasopharynx culture models"),
 128: ("review", "pubType Review; systemic tumour immune environment review"),
 129: ("not_NPC_disease", "re-analysis of four COVID-19 RNA-seq datasets"),
 130: ("not_NPC_disease", "nasal ciliated cells in severe COVID-19"),
 131: ("review", "pubType Review; NPC tumour immune microenvironment review"),
 132: ("not_NPC_disease", "COVID-19 co-morbidity case report in HCC and CRC patients"),
 134: ("not_NPC_disease", "COVID-19 cell-cell communication workflow"),
 136: ("not_NPC_disease", "COPD nasopharyngeal and bronchial organoids"),
 137: ("not_NPC_disease", "local intrinsic immunity in severe COVID-19"),
 138: ("not_NPC_disease", "COVID-19-associated IgA nephropathy kidney biopsy"),
 139: ("not_NPC_disease", "immune checkpoint receptors in SARS-CoV-2 infection"),
 142: ("review", "pubType Review; SARS-CoV-2 infection of airway epithelial cells"),
 144: ("not_NPC_disease", "SARS-CoV-2 infection of oral cavity and saliva"),
 145: ("review", "pubType Review; mucosal immunity to SARS-CoV-2"),
 146: ("cell_line_or_xenograft_only", "nasopharyngeal air-liquid-interface cultures from healthy donors; EBV infection model, no NPC tumour"),
 148: ("not_NPC_disease", "nasopharyngeal immune kinetics in asymptomatic COVID-19 carriers"),
 149: ("not_NPC_disease", "CDHR3 and otitis media susceptibility"),
 150: ("not_NPC_disease", "alveolar macrophages in critical COVID-19"),
 151: ("review", "pubType Review; NPC stromal and immune landscape review"),
 152: ("not_NPC_disease", "autotaxin levels in severe COVID-19"),
 153: ("not_NPC_disease", "FUT2 variant and otitis media nasopharyngeal microbiota"),
 154: ("methods_tool_paper", "KeyPathwayMineR R package"),
 155: ("cell_line_or_xenograft_only", "air-liquid-interface nasopharyngeal culture EBV infection model preprint"),
 156: ("not_NPC_disease", "oral SARS-CoV-2 infection and transmission atlas preprint"),
 157: ("not_NPC_disease", "hypertensive COVID-19 airway inflammation preprint"),
 158: ("not_NPC_disease", "airway epithelium-immune crosstalk in COVID-19 preprint"),
 161: ("not_NPC_disease", "COVID-19 severity and airway epithelium-immune interactions"),
 165: ("not_nasopharyngeal_site", "lymphoepithelioma-like carcinoma of the lung, not nasopharynx"),
 166: ("not_NPC_disease", "mouse model of oral carcinogenesis"),
 167: ("not_nasopharyngeal_site", "lung lymphoepithelioma-like carcinoma case report preprint"),
 168: ("cell_line_or_xenograft_only", "Dovitinib in cancer cell lines; single-cell imaging of mitosis, not single-cell genomics"),
 169: ("not_NPC_disease", "adenoid CD5+ B cells by flow cytometry/ELISPOT in children"),
 53:  ("cell_line_or_xenograft_only", "NPC43 EBV-positive NPC cell line under lytic induction"),
 35:  ("no_retrievable_identifier", "record carries neither PMID nor DOI; fails spec hard rule 4"),
}
